- name: Create docker database
  docker_container:
    name: database
    image: renizmy/tp2-devops:tp_database
    restart: yes
    networks:
      - name: app-network
    env:
      POSTGRES_PASSWORD: "{{ db_password }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_DB: "{{ db_name }}"